export const mcq = {
  webDev: [
    { question: "Which HTML tag is used to define the largest heading?", options: ["<h6>", "<h1>", "<head>", "<header>"], answer: "<h1>" },
    { question: "Which CSS property controls the text size?", options: ["font-style", "text-size", "font-size", "text-style"], answer: "font-size" },
    { question: "In JavaScript, which keyword is used to declare a variable?", options: ["var", "let", "both var and let", "const"], answer: "both var and let" },
    { question: "Which HTTP status code means 'Not Found'?", options: ["200", "301", "404", "500"], answer: "404" },
    { question: "Which HTML attribute is used to define inline styles?", options: ["class", "style", "font", "styles"], answer: "style" },
    { question: "Which CSS property is used to change text color?", options: ["fgcolor", "color", "font-color", "text-color"], answer: "color" },
    { question: "Which JavaScript method is used to select an element by ID?", options: ["getElementById()", "querySelector()", "getElementsByClassName()", "getId()"], answer: "getElementById()" },
    { question: "What does CSS stand for?", options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], answer: "Cascading Style Sheets" },
    { question: "Which HTML element is used to create a hyperlink?", options: ["<a>", "<link>", "<href>", "<hyper>"], answer: "<a>" },
    { question: "Which CSS property controls the background color?", options: ["bgcolor", "background-color", "color", "background"], answer: "background-color" },
    { question: "Which HTML element is used for the largest heading?", options: ["<h1>", "<heading>", "<h6>", "<head>"], answer: "<h1>" },
    { question: "Which tag is used to insert an image?", options: ["<img>", "<image>", "<src>", "<pic>"], answer: "<img>" },
    { question: "Which JavaScript method is used to write to the console?", options: ["print()", "log()", "console.log()", "document.write()"], answer: "console.log()" },
    { question: "Which HTML tag is used to define an unordered list?", options: ["<ol>", "<ul>", "<li>", "<list>"], answer: "<ul>" },
    { question: "Which CSS property sets the spacing between lines of text?", options: ["spacing", "line-height", "text-spacing", "line-spacing"], answer: "line-height" },
    { question: "Which HTML5 element is used to play video files?", options: ["<movie>", "<video>", "<media>", "<play>"], answer: "<video>" },
    { question: "Which HTML tag is used to create a table row?", options: ["<td>", "<th>", "<tr>", "<row>"], answer: "<tr>" },
    { question: "Which CSS property sets the size of a font?", options: ["font-size", "text-size", "font-weight", "font-style"], answer: "font-size" },
    { question: "Which HTML tag is used to make text bold?", options: ["<b>", "<bold>", "<strong>", "both <b> and <strong>"], answer: "both <b> and <strong>" },
    { question: "Which JavaScript method is used to change HTML content?", options: ["innerHTML", "changeHTML", "replaceHTML", "setHTML"], answer: "innerHTML" },
    { question: "Which HTML tag is used for a numbered list?", options: ["<ul>", "<ol>", "<list>", "<li>"], answer: "<ol>" },
    { question: "Which CSS unit is relative to the parent element’s font size?", options: ["px", "em", "%", "rem"], answer: "em" },
    { question: "Which HTTP method is used to submit data to a server?", options: ["GET", "POST", "PUT", "DELETE"], answer: "POST" },
    { question: "Which CSS property sets the space outside an element?", options: ["padding", "margin", "border", "spacing"], answer: "margin" },
    { question: "Which HTML element is used to display a scalar measurement?", options: ["<meter>", "<progress>", "<scale>", "<gauge>"], answer: "<meter>" },
    { question: "Which HTML tag is used to embed a document from another source?", options: ["<iframe>", "<embed>", "<object>", "<link>"], answer: "<iframe>" },
    { question: "Which CSS property sets the transparency?", options: ["opacity", "visibility", "alpha", "filter"], answer: "opacity" },
    { question: "Which protocol is used for secure communication over the web?", options: ["HTTP", "HTTPS", "FTP", "SMTP"], answer: "HTTPS" },
    { question: "Which HTML tag is used for short quotations?", options: ["<q>", "<quote>", "<blockquote>", "<shortquote>"], answer: "<q>" },
    { question: "Which CSS property sets the style of the list item marker?", options: ["list-type", "list-style", "marker-style", "bullet-style"], answer: "list-style" },
    { question: "Which HTML attribute specifies an alternate text for an image?", options: ["alt", "title", "src", "caption"], answer: "alt" },
    { question: "Which CSS function is used to apply a transformation?", options: ["transform()", "matrix()", "rotate()", "skew()"], answer: "transform()" },
    { question: "Which HTML tag is used to define a footer?", options: ["<footer>", "<bottom>", "<end>", "<foot>"], answer: "<footer>" },
    { question: "Which CSS property sets the order of flex items?", options: ["flex-order", "order", "z-index", "align"], answer: "order" },
    { question: "Which HTML attribute specifies the URL of a linked resource?", options: ["src", "href", "link", "url"], answer: "href" },
    { question: "Which CSS property controls element stacking?", options: ["z-index", "stack", "position", "layer"], answer: "z-index" },
    { question: "Which HTML tag is used to create a form?", options: ["<form>", "<input>", "<fieldset>", "<textarea>"], answer: "<form>" },
    { question: "Which CSS property makes text italic?", options: ["italic", "font-italic", "font-style", "style"], answer: "font-style" },
    { question: "Which HTML tag is used for a table cell?", options: ["<td>", "<tr>", "<th>", "<cell>"], answer: "<td>" },
    { question: "Which CSS property controls how content overflows?", options: ["overflow", "clip", "display", "visibility"], answer: "overflow" },
    { question: "Which HTML tag is used to display a progress bar?", options: ["<progress>", "<meter>", "<bar>", "<status>"], answer: "<progress>" },
    { question: "Which CSS property changes the cursor style?", options: ["cursor", "pointer", "mouse", "hover"], answer: "cursor" },
    { question: "Which HTML tag is used for navigation links?", options: ["<nav>", "<menu>", "<navigation>", "<links>"], answer: "<nav>" },
    { question: "Which CSS property specifies the space inside an element?", options: ["margin", "padding", "spacing", "border"], answer: "padding" },
    { question: "Which HTML tag is used to group block-level content?", options: ["<div>", "<span>", "<section>", "<group>"], answer: "<div>" },
    { question: "Which CSS property specifies the shadow of text?", options: ["text-shadow", "shadow", "font-shadow", "drop-shadow"], answer: "text-shadow" },
    { question: "Which HTML element is used for inline text grouping?", options: ["<span>", "<div>", "<p>", "<label>"], answer: "<span>" },
    { question: "Which CSS property sets the maximum width of an element?", options: ["width", "max-width", "min-width", "size"], answer: "max-width" },
    { question: "Which HTML tag is used to insert a line break?", options: ["<br>", "<lb>", "<break>", "<nl>"], answer: "<br>" },
    { question: "Which CSS property sets the background image?", options: ["background", "background-image", "bg-image", "image"], answer: "background-image" },
    { question: "Which HTML tag is used for the document title?", options: ["<title>", "<head>", "<header>", "<caption>"], answer: "<title>" },
    { question: "Which CSS property aligns items in flexbox?", options: ["align-items", "align", "justify", "align-content"], answer: "align-items" },
    { question: "Which HTML tag is used to create a dropdown list?", options: ["<select>", "<dropdown>", "<list>", "<menu>"], answer: "<select>" },
    { question: "Which CSS property specifies whether text wraps?", options: ["white-space", "wrap", "text-wrap", "word-wrap"], answer: "white-space" },
    { question: "Which HTML tag is used for emphasized text?", options: ["<em>", "<italic>", "<strong>", "<i>"], answer: "<em>" },
    { question: "Which CSS property specifies the border width?", options: ["border-width", "border-size", "border", "thickness"], answer: "border-width" },
    { question: "Which HTML tag is used to define a document section?", options: ["<section>", "<div>", "<part>", "<area>"], answer: "<section>" },
    { question: "Which CSS property controls the element’s position type?", options: ["position", "location", "placement", "display"], answer: "position" },
    { question: "Which HTML tag is used for multi-line text input?", options: ["<textarea>", "<input>", "<textbox>", "<multiline>"], answer: "<textarea>" },
    { question: "Which CSS property sets the background repeat?", options: ["background-repeat", "repeat", "bg-repeat", "repeat-image"], answer: "background-repeat" },
    { question: "Which HTML tag is used to mark up a quotation block?", options: ["<blockquote>", "<quote>", "<q>", "<cite>"], answer: "<blockquote>" },
    { question: "Which CSS property sets how flex items are spaced?", options: ["justify-content", "align-items", "spacing", "gap"], answer: "justify-content" },
    { question: "Which HTML tag is used to define the main content?", options: ["<main>", "<body>", "<article>", "<content>"], answer: "<main>" },
    { question: "Which CSS property sets the font weight?", options: ["font-weight", "font-bold", "boldness", "font-style"], answer: "font-weight" },
    { question: "Which HTML tag is used to group form controls?", options: ["<fieldset>", "<form>", "<group>", "<label>"], answer: "<fieldset>" },
    { question: "Which CSS property specifies the grid template columns?", options: ["grid-template-columns", "grid-columns", "template-columns", "columns"], answer: "grid-template-columns" },
    { question: "Which HTML tag is used for short inline code snippets?", options: ["<code>", "<pre>", "<kbd>", "<var>"], answer: "<code>" },
    { question: "Which CSS property defines the transition speed?", options: ["transition-duration", "duration", "speed", "time"], answer: "transition-duration" },
    { question: "Which HTML tag is used for marking text?", options: ["<mark>", "<highlight>", "<em>", "<b>"], answer: "<mark>" }
  ],
  ds : [
  { question: "Which data structure uses FIFO order?", options: ["Stack", "Queue", "Tree", "Graph"], answer: "Queue" },
  { question: "Which traversal method visits the root node first, then left, then right?", options: ["Inorder", "Preorder", "Postorder", "Level order"], answer: "Preorder" },
  { question: "Which of the following is a non-linear data structure?", options: ["Array", "Linked List", "Stack", "Graph"], answer: "Graph" },
  { question: "Which operation removes the top element of a stack?", options: ["pop()", "push()", "enqueue()", "dequeue()"], answer: "pop()" },
  { question: "Which data structure is best suited for implementing recursion?", options: ["Queue", "Stack", "Linked List", "Array"], answer: "Stack" },
  { question: "Which traversal of a binary tree gives the nodes in sorted order for BST?", options: ["Preorder", "Inorder", "Postorder", "Level order"], answer: "Inorder" },
  { question: "Which data structure is used in BFS algorithm?", options: ["Stack", "Queue", "Heap", "Array"], answer: "Queue" },
  { question: "Which data structure allows insertion and deletion from both ends?", options: ["Deque", "Queue", "Stack", "Priority Queue"], answer: "Deque" },
  { question: "Which searching algorithm works on sorted arrays only?", options: ["Linear Search", "Binary Search", "DFS", "BFS"], answer: "Binary Search" },
  { question: "What is the time complexity of inserting at the beginning of a linked list?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: "O(1)" },
  { question: "Which data structure uses LIFO order?", options: ["Queue", "Stack", "Heap", "Graph"], answer: "Stack" },
  { question: "Which type of linked list has nodes connected in both directions?", options: ["Singly Linked List", "Circular Linked List", "Doubly Linked List", "Skip List"], answer: "Doubly Linked List" },
  { question: "Which heap type is used in Dijkstra’s algorithm?", options: ["Max Heap", "Min Heap", "Fibonacci Heap", "Binary Heap"], answer: "Min Heap" },
  { question: "Which data structure is most suitable for implementing undo operations?", options: ["Queue", "Stack", "Heap", "Tree"], answer: "Stack" },
  { question: "Which data structure is used to store key-value pairs?", options: ["Array", "Hash Table", "Stack", "Queue"], answer: "Hash Table" },
  { question: "Which operation retrieves the front element of a queue without removing it?", options: ["dequeue()", "peek()", "pop()", "top()"], answer: "peek()" },
  { question: "Which algorithm is used for finding the shortest path in graphs?", options: ["Prim's", "Dijkstra's", "Kruskal's", "DFS"], answer: "Dijkstra's" },
  { question: "Which data structure is used in function call management in programming?", options: ["Queue", "Stack", "Array", "Heap"], answer: "Stack" },
  { question: "Which data structure is implemented using two stacks?", options: ["Queue", "Heap", "Graph", "Deque"], answer: "Queue" },
  { question: "Which is the best data structure for priority scheduling?", options: ["Queue", "Priority Queue", "Stack", "Array"], answer: "Priority Queue" },
  { question: "Which data structure helps in detecting cycles in a graph?", options: ["Stack", "Union-Find", "Queue", "Heap"], answer: "Union-Find" },
  { question: "Which traversal method is used in Depth-First Search?", options: ["Preorder", "Inorder", "Postorder", "Any of these"], answer: "Any of these" },
  { question: "What is the worst-case time complexity of QuickSort?", options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], answer: "O(n^2)" },
  { question: "Which traversal method is used in Breadth-First Search?", options: ["Preorder", "Postorder", "Level order", "Inorder"], answer: "Level order" },
  { question: "Which data structure is used in the backtracking algorithm?", options: ["Queue", "Stack", "Array", "Heap"], answer: "Stack" },
  { question: "Which data structure is most efficient for searching when data is static?", options: ["Hash Table", "Array", "Binary Search Tree", "Heap"], answer: "Binary Search Tree" },
  { question: "Which sorting algorithm is stable?", options: ["Merge Sort", "QuickSort", "Heap Sort", "Selection Sort"], answer: "Merge Sort" },
  { question: "Which algorithm is used for minimum spanning tree?", options: ["Dijkstra's", "Prim's", "DFS", "BFS"], answer: "Prim's" },
  { question: "Which data structure can be used to evaluate postfix expressions?", options: ["Queue", "Stack", "Heap", "Array"], answer: "Stack" },
  { question: "Which searching method has O(1) complexity?", options: ["Binary Search", "Linear Search", "Hashing", "DFS"], answer: "Hashing" },
  { question: "Which traversal method uses recursion in binary trees?", options: ["Inorder", "Preorder", "Postorder", "All of these"], answer: "All of these" },
  { question: "Which sorting algorithm works on the principle of divide and conquer?", options: ["QuickSort", "Merge Sort", "Both", "Heap Sort"], answer: "Both" },
  { question: "Which data structure is used in implementing a browser's back button?", options: ["Queue", "Stack", "Deque", "Linked List"], answer: "Stack" },
  { question: "Which data structure can be circular?", options: ["Queue", "Linked List", "Both", "None"], answer: "Both" },
  { question: "Which tree traversal visits nodes in the order Left-Root-Right?", options: ["Inorder", "Preorder", "Postorder", "Level order"], answer: "Inorder" },
  { question: "Which graph representation uses less memory for sparse graphs?", options: ["Adjacency Matrix", "Adjacency List", "Incidence Matrix", "Edge List"], answer: "Adjacency List" },
  { question: "Which algorithm is used for topological sorting?", options: ["DFS", "BFS", "Dijkstra", "Prim"], answer: "DFS" },
  { question: "Which data structure is best for implementing a dictionary?", options: ["Array", "Hash Table", "Stack", "Queue"], answer: "Hash Table" },
  { question: "Which traversal method processes nodes in FIFO order?", options: ["DFS", "BFS", "Inorder", "Postorder"], answer: "BFS" },
  { question: "Which is a balanced binary search tree?", options: ["AVL Tree", "Red-Black Tree", "B-Tree", "All of these"], answer: "All of these" },
  { question: "Which sorting algorithm is in-place?", options: ["Merge Sort", "QuickSort", "Heap Sort", "Both QuickSort and Heap Sort"], answer: "Both QuickSort and Heap Sort" },
  { question: "Which heap type has the smallest element at the root?", options: ["Max Heap", "Min Heap", "Binary Heap", "Fibonacci Heap"], answer: "Min Heap" },
  { question: "Which search algorithm works without sorted data?", options: ["Linear Search", "Binary Search", "Interpolation Search", "Jump Search"], answer: "Linear Search" },
  { question: "Which tree has all levels filled except possibly the last?", options: ["Complete Binary Tree", "Full Binary Tree", "Perfect Binary Tree", "AVL Tree"], answer: "Complete Binary Tree" },
  { question: "Which traversal is best for copying a tree?", options: ["Inorder", "Preorder", "Postorder", "Level order"], answer: "Preorder" },
  { question: "Which algorithm finds the shortest path in unweighted graphs?", options: ["BFS", "DFS", "Dijkstra", "Bellman-Ford"], answer: "BFS" },
  { question: "Which data structure supports searching, insertion, and deletion in O(log n)?", options: ["Array", "BST", "Heap", "Hash Table"], answer: "BST" },
  { question: "Which graph type has no cycles?", options: ["Cyclic Graph", "Acyclic Graph", "Directed Graph", "Weighted Graph"], answer: "Acyclic Graph" },
  { question: "Which algorithm is used to detect negative weight cycles?", options: ["Dijkstra", "Bellman-Ford", "Prim", "Kruskal"], answer: "Bellman-Ford" },
  { question: "Which data structure is best for matching parentheses in code?", options: ["Queue", "Stack", "Array", "Heap"], answer: "Stack" },
  { question: "Which tree has height O(log n)?", options: ["AVL Tree", "Red-Black Tree", "B-Tree", "All of these"], answer: "All of these" },
  { question: "Which sorting algorithm is best for linked lists?", options: ["Merge Sort", "QuickSort", "Bubble Sort", "Heap Sort"], answer: "Merge Sort" },
  { question: "Which data structure supports random access in O(1)?", options: ["Array", "Linked List", "Stack", "Queue"], answer: "Array" },
  { question: "Which algorithm uses a pivot element?", options: ["QuickSort", "Merge Sort", "Heap Sort", "Counting Sort"], answer: "QuickSort" },
  { question: "Which algorithm is not comparison-based?", options: ["QuickSort", "Merge Sort", "Counting Sort", "Heap Sort"], answer: "Counting Sort" },
  { question: "Which tree has keys stored in sorted order?", options: ["Binary Search Tree", "Heap", "Trie", "BFS Tree"], answer: "Binary Search Tree" },
  { question: "Which traversal is used for expression trees to get postfix?", options: ["Inorder", "Preorder", "Postorder", "Level order"], answer: "Postorder" },
  { question: "Which is the most memory-efficient for sparse matrices?", options: ["2D Array", "Linked List", "Dictionary of Keys", "All of these"], answer: "Dictionary of Keys" },
  { question: "Which algorithm is used for cycle detection in graphs?", options: ["DFS", "BFS", "Dijkstra", "Prim"], answer: "DFS" },
  { question: "Which data structure is used in a LRU cache?", options: ["Stack + Array", "HashMap + Doubly Linked List", "Heap", "Trie"], answer: "HashMap + Doubly Linked List" }
    ],
    ml : [
  { question: "Which type of learning uses labeled data?", options: ["Supervised", "Unsupervised", "Reinforcement", "Deep"], answer: "Supervised" },
  { question: "Which algorithm is used for classification problems?", options: ["Linear Regression", "K-Means", "Logistic Regression", "Apriori"], answer: "Logistic Regression" },
  { question: "Which metric is suitable for imbalanced classification?", options: ["Accuracy", "Precision-Recall", "MAE", "MSE"], answer: "Precision-Recall" },
  { question: "Which activation function outputs values between 0 and 1?", options: ["ReLU", "Sigmoid", "Tanh", "Softmax"], answer: "Sigmoid" },
  { question: "Which library is primarily used for deep learning?", options: ["NumPy", "Pandas", "TensorFlow", "Matplotlib"], answer: "TensorFlow" },
  { question: "Which type of machine learning uses reward-based training?", options: ["Supervised", "Unsupervised", "Reinforcement", "Semi-supervised"], answer: "Reinforcement" },
  { question: "Which algorithm is used for clustering?", options: ["K-Means", "Logistic Regression", "Linear Regression", "Decision Tree"], answer: "K-Means" },
  { question: "Which model is used for predicting continuous values?", options: ["Classification", "Regression", "Clustering", "Association"], answer: "Regression" },
  { question: "Which metric is used for regression error?", options: ["MSE", "Accuracy", "Recall", "F1 Score"], answer: "MSE" },
  { question: "Which algorithm is known as a lazy learner?", options: ["Decision Tree", "KNN", "SVM", "Naive Bayes"], answer: "KNN" },
  { question: "Which term refers to fitting the training data too well?", options: ["Overfitting", "Underfitting", "Bias", "Variance"], answer: "Overfitting" },
  { question: "Which ML task finds hidden patterns in data without labels?", options: ["Supervised", "Unsupervised", "Reinforcement", "Regression"], answer: "Unsupervised" },
  { question: "Which optimization algorithm is widely used for training neural networks?", options: ["Gradient Descent", "Bellman-Ford", "Prim’s", "Kruskal’s"], answer: "Gradient Descent" },
  { question: "Which ML concept is the trade-off between bias and variance?", options: ["Regularization", "Bias-Variance Tradeoff", "Gradient Vanishing", "Learning Rate Decay"], answer: "Bias-Variance Tradeoff" },
  { question: "Which regularization technique uses L1 norm?", options: ["Lasso", "Ridge", "Elastic Net", "Dropout"], answer: "Lasso" },
  { question: "Which ML algorithm is used for market basket analysis?", options: ["Apriori", "K-Means", "SVM", "Linear Regression"], answer: "Apriori" },
  { question: "Which function is used in logistic regression?", options: ["Sigmoid", "ReLU", "Tanh", "Softmax"], answer: "Sigmoid" },
  { question: "Which type of machine learning combines labeled and unlabeled data?", options: ["Supervised", "Unsupervised", "Semi-supervised", "Reinforcement"], answer: "Semi-supervised" },
  { question: "Which evaluation method splits data into training and test sets multiple times?", options: ["Cross-Validation", "Holdout", "Bootstrap", "Resampling"], answer: "Cross-Validation" },
  { question: "Which term describes a model that performs poorly on training and test data?", options: ["Overfitting", "Underfitting", "Bias", "Variance"], answer: "Underfitting" },
  { question: "Which algorithm is best for dimensionality reduction?", options: ["PCA", "K-Means", "SVM", "Naive Bayes"], answer: "PCA" },
  { question: "Which metric is used to measure the purity of a split in Decision Trees?", options: ["Entropy", "Recall", "MSE", "R-Squared"], answer: "Entropy" },
  { question: "Which algorithm uses hyperplanes to classify data?", options: ["SVM", "KNN", "Naive Bayes", "Decision Tree"], answer: "SVM" },
  { question: "Which method helps in preventing overfitting in neural networks?", options: ["Dropout", "Batch Normalization", "Data Augmentation", "All of these"], answer: "All of these" },
  { question: "Which loss function is used in linear regression?", options: ["MSE", "Cross-Entropy", "Hinge Loss", "Log Loss"], answer: "MSE" },
  { question: "Which ML algorithm uses decision boundaries?", options: ["SVM", "Naive Bayes", "Apriori", "PCA"], answer: "SVM" },
  { question: "Which feature scaling method subtracts mean and divides by std deviation?", options: ["Standardization", "Normalization", "Log Transformation", "Min-Max Scaling"], answer: "Standardization" },
  { question: "Which ensemble method uses bootstrapping?", options: ["Bagging", "Boosting", "Stacking", "Voting"], answer: "Bagging" },
  { question: "Which ML approach uses multiple weak learners to create a strong learner?", options: ["Boosting", "Bagging", "Stacking", "Voting"], answer: "Boosting" },
  { question: "Which algorithm is used in Google's PageRank?", options: ["Markov Chains", "K-Means", "SVM", "Linear Regression"], answer: "Markov Chains" },
  { question: "Which ML technique deals with imbalance by oversampling?", options: ["SMOTE", "Bagging", "PCA", "Dropout"], answer: "SMOTE" },
  { question: "Which deep learning architecture is used for image data?", options: ["CNN", "RNN", "GAN", "Transformer"], answer: "CNN" },
  { question: "Which deep learning architecture is best for sequential data?", options: ["RNN", "CNN", "GAN", "DBN"], answer: "RNN" },
  { question: "Which problem occurs when gradients become too small?", options: ["Vanishing Gradient", "Exploding Gradient", "Overfitting", "Underfitting"], answer: "Vanishing Gradient" },
  { question: "Which type of machine learning uses trial and error to learn?", options: ["Reinforcement", "Supervised", "Unsupervised", "Self-Supervised"], answer: "Reinforcement" },
  { question: "Which algorithm is used for spam filtering?", options: ["Naive Bayes", "SVM", "KNN", "Decision Tree"], answer: "Naive Bayes" },
  { question: "Which term describes using past data to predict future events?", options: ["Predictive Modeling", "Descriptive Analysis", "Diagnostic Analysis", "Prescriptive Analysis"], answer: "Predictive Modeling" },
  { question: "Which ML algorithm is a probabilistic classifier?", options: ["Naive Bayes", "SVM", "KNN", "Decision Tree"], answer: "Naive Bayes" },
  { question: "Which algorithm is used for outlier detection?", options: ["Isolation Forest", "Random Forest", "SVM", "KNN"], answer: "Isolation Forest" },
  { question: "Which process converts raw data into features?", options: ["Feature Engineering", "Model Training", "Evaluation", "Normalization"], answer: "Feature Engineering" },
  { question: "Which concept in ML refers to the number of features?", options: ["Dimensionality", "Bias", "Variance", "Hyperparameter"], answer: "Dimensionality" },
  { question: "Which evaluation metric is harmonic mean of precision and recall?", options: ["F1 Score", "Accuracy", "MSE", "AUC"], answer: "F1 Score" },
  { question: "Which model architecture is used in GPT?", options: ["Transformer", "RNN", "CNN", "LSTM"], answer: "Transformer" },
  { question: "Which ML method combines outputs of different models?", options: ["Ensemble Learning", "Boosting", "Bagging", "Stacking"], answer: "Ensemble Learning" },
  { question: "Which loss function is used for multi-class classification?", options: ["Categorical Cross-Entropy", "MSE", "Hinge Loss", "Binary Cross-Entropy"], answer: "Categorical Cross-Entropy" },
  { question: "Which ML concept is tuning model parameters?", options: ["Hyperparameter Optimization", "Training", "Testing", "Validation"], answer: "Hyperparameter Optimization" },
  { question: "Which ML algorithm splits data using Gini Index?", options: ["Decision Tree", "SVM", "KNN", "Naive Bayes"], answer: "Decision Tree" },
  { question: "Which neural network type is generative?", options: ["GAN", "CNN", "RNN", "LSTM"], answer: "GAN" },
  { question: "Which optimizer is an improvement over SGD?", options: ["Adam", "Adagrad", "RMSProp", "All of these"], answer: "All of these" },
  { question: "Which ML technique reduces overfitting by limiting features?", options: ["Regularization", "Dropout", "Bagging", "PCA"], answer: "Regularization" },
  { question: "Which ML algorithm predicts probabilities?", options: ["Logistic Regression", "Linear Regression", "KNN", "SVM"], answer: "Logistic Regression" },
  { question: "Which technique is used for anomaly detection in time-series?", options: ["ARIMA", "KNN", "SVM", "Decision Tree"], answer: "ARIMA" },
  { question: "Which library is mainly used for numerical computation in Python?", options: ["NumPy", "Pandas", "Matplotlib", "Scikit-learn"], answer: "NumPy" },
  { question: "Which method is used to prevent vanishing gradients?", options: ["ReLU", "Sigmoid", "Tanh", "Softmax"], answer: "ReLU" },
  { question: "Which term refers to a model's ability to generalize to unseen data?", options: ["Generalization", "Overfitting", "Underfitting", "Bias"], answer: "Generalization" },
  { question: "Which deep learning model is used for text translation?", options: ["Transformer", "CNN", "RNN", "GAN"], answer: "Transformer" },
  { question: "Which type of ML task involves grouping data?", options: ["Clustering", "Classification", "Regression", "Prediction"], answer: "Clustering" },
  { question: "Which ML model uses a tree-like graph?", options: ["Decision Tree", "KNN", "SVM", "Naive Bayes"], answer: "Decision Tree" },
  { question: "Which ML approach trains models on subsets of data?", options: ["Bagging", "Boosting", "Stacking", "Regularization"], answer: "Bagging" }
],
c : [
  { question: "Which header file is needed for printf() and scanf()?", options: ["<stdlib.h>", "<stdio.h>", "<string.h>", "<math.h>"], answer: "<stdio.h>" },
  { question: "What is the default return type of main() in C?", options: ["int", "void", "char", "float"], answer: "int" },
  { question: "Which operator is used to access the value at an address?", options: ["&", "*", "->", "."], answer: "*" },
  { question: "Which keyword is used to define a constant in C?", options: ["const", "constant", "#define", "Both const and #define"], answer: "Both const and #define" },
  { question: "Which format specifier is used for integers in printf()?", options: ["%d", "%f", "%c", "%s"], answer: "%d" },
  { question: "Which function is used to find the length of a string?", options: ["strlength()", "strlen()", "size()", "len()"], answer: "strlen()" },
  { question: "Which storage class makes a variable retain value between function calls?", options: ["auto", "register", "static", "extern"], answer: "static" },
  { question: "Which loop is guaranteed to execute at least once?", options: ["for", "while", "do-while", "None"], answer: "do-while" },
  { question: "Which symbol is used for a single-line comment in C?", options: ["//", "/*", "#", "--"], answer: "//" },
  { question: "What is the size of int on a 32-bit system?", options: ["2 bytes", "4 bytes", "8 bytes", "Depends on compiler"], answer: "4 bytes" },
  { question: "Which operator is used for pointer to a structure?", options: ["*", ".", "->", "&"], answer: "->" },
  { question: "Which keyword is used to exit from a loop?", options: ["break", "exit", "continue", "stop"], answer: "break" },
  { question: "Which function is used to allocate memory dynamically?", options: ["malloc()", "alloc()", "calloc()", "Both malloc() and calloc()"], answer: "Both malloc() and calloc()" },
  { question: "Which header file contains mathematical functions like sqrt()?", options: ["<stdlib.h>", "<math.h>", "<stdio.h>", "<ctype.h>"], answer: "<math.h>" },
  { question: "Which function compares two strings in C?", options: ["strcomp()", "strcmp()", "compare()", "stringcmp()"], answer: "strcmp()" },
  { question: "Which escape sequence is used for a new line?", options: ["\\n", "\\t", "\\r", "\\b"], answer: "\\n" },
  { question: "Which keyword is used to define an enumeration?", options: ["enum", "enumerate", "enumtype", "list"], answer: "enum" },
  { question: "Which function terminates a program immediately?", options: ["stop()", "end()", "exit()", "terminate()"], answer: "exit()" },
  { question: "Which format specifier is used for floating-point numbers?", options: ["%d", "%f", "%c", "%lf"], answer: "%f" },
  { question: "Which keyword is used to create a structure?", options: ["struct", "structure", "record", "define"], answer: "struct" },
  { question: "Which function copies one string into another?", options: ["strcopy()", "strcpy()", "copystr()", "copy()"], answer: "strcpy()" },
  { question: "Which operator is used for bitwise AND?", options: ["&&", "&", "|", "and"], answer: "&" },
  { question: "Which function reads a single character from the user?", options: ["getchar()", "scanf()", "read()", "input()"], answer: "getchar()" },
  { question: "Which function opens a file in C?", options: ["fopen()", "open()", "fileopen()", "startfile()"], answer: "fopen()" },
  { question: "Which file mode in fopen() is used to write only?", options: ["r", "w", "a", "rw"], answer: "w" },
  { question: "Which function is used to close a file?", options: ["fileclose()", "fclose()", "close()", "endfile()"], answer: "fclose()" },
  { question: "Which loop is best for iterating over a known number of times?", options: ["while", "do-while", "for", "None"], answer: "for" },
  { question: "Which operator returns the remainder of division?", options: ["%", "/", "//", "mod"], answer: "%" },
  { question: "Which keyword is used to include a header file?", options: ["import", "include", "#include", "use"], answer: "#include" },
  { question: "Which storage class is used for global variables?", options: ["auto", "static", "extern", "register"], answer: "extern" },
  { question: "Which function is used to set memory to zero?", options: ["memset()", "bzero()", "clear()", "zero()"], answer: "memset()" },
  { question: "Which keyword is used for defining a constant integer?", options: ["const", "static", "#define", "Both const and #define"], answer: "Both const and #define" },
  { question: "Which operator is used for logical OR?", options: ["|", "||", "or", "Any"], answer: "||" },
  { question: "Which function is used to print a character?", options: ["printf()", "putchar()", "print()", "display()"], answer: "putchar()" },
  { question: "Which keyword is used to define a union?", options: ["union", "combine", "group", "struct"], answer: "union" },
  { question: "Which function is used to concatenate two strings?", options: ["strconcat()", "strcat()", "concat()", "append()"], answer: "strcat()" },
  { question: "Which function reads a string from the user?", options: ["gets()", "scanf()", "getline()", "readstr()"], answer: "gets()" },
  { question: "Which statement transfers control to a labeled statement?", options: ["goto", "jump", "transfer", "skip"], answer: "goto" },
  { question: "Which function returns the absolute value of an integer?", options: ["abs()", "fabs()", "absolute()", "pos()"], answer: "abs()" },
  { question: "Which type modifier is used to increase size of int?", options: ["long", "short", "unsigned", "signed"], answer: "long" },
  { question: "Which format specifier is used for characters?", options: ["%d", "%f", "%c", "%s"], answer: "%c" },
  { question: "Which storage class stores variables in CPU registers?", options: ["auto", "register", "static", "extern"], answer: "register" },
  { question: "Which function is used to free dynamically allocated memory?", options: ["delete()", "remove()", "free()", "clear()"], answer: "free()" },
  { question: "Which keyword is used to skip current loop iteration?", options: ["break", "skip", "continue", "pass"], answer: "continue" },
  { question: "Which operator is used for logical AND?", options: ["&", "&&", "and", "Both & and &&"], answer: "&&" },
  { question: "Which function converts a string to an integer?", options: ["strtoint()", "atoi()", "parseInt()", "toint()"], answer: "atoi()" },
  { question: "Which preprocessor directive is used to define macros?", options: ["#define", "#macro", "#const", "#set"], answer: "#define" },
  { question: "Which header file is used for string functions?", options: ["<string.h>", "<stdlib.h>", "<stdio.h>", "<ctype.h>"], answer: "<string.h>" },
  { question: "Which keyword is used to return a value from a function?", options: ["return", "give", "exit", "output"], answer: "return" },
  { question: "Which operator is used to find size of a variable?", options: ["length", "sizeof", "size", "measure"], answer: "sizeof" },
  { question: "Which function is used to write a string to a file?", options: ["fputs()", "puts()", "writefile()", "fprintf()"], answer: "fputs()" },
  { question: "Which function writes formatted output to a string?", options: ["sprintf()", "printf()", "strprintf()", "format()"], answer: "sprintf()" },
  { question: "Which keyword is used to define a macro with arguments?", options: ["#define", "#macro", "#argmacro", "#set"], answer: "#define" },
  { question: "Which function searches a character in a string?", options: ["strchr()", "strfind()", "index()", "findchar()"], answer: "strchr()" },
  { question: "Which header file is needed for dynamic memory allocation?", options: ["<stdlib.h>", "<stdio.h>", "<malloc.h>", "<memory.h>"], answer: "<stdlib.h>" },
  { question: "Which function converts a character to lowercase?", options: ["tolower()", "lower()", "charlower()", "downcase()"], answer: "tolower()" },
  { question: "Which keyword is used to create an infinite loop?", options: ["while(1)", "loop", "for(;;)", "Both while(1) and for(;;)"], answer: "Both while(1) and for(;;)" },
  { question: "Which function compares n characters of two strings?", options: ["strncmp()", "strcmp()", "strncomp()", "stringcmp()"], answer: "strncmp()" },
  { question: "Which operator increments a value by 1?", options: ["++", "+", "add", "inc"], answer: "++" },
  { question: "Which format specifier is used for double values?", options: ["%lf", "%d", "%f", "%ld"], answer: "%lf" },
  { question: "Which keyword is used for conditional branching?", options: ["if", "switch", "goto", "All of these"], answer: "All of these" },
  { question: "Which function finds the first occurrence of a substring?", options: ["strstr()", "substr()", "find()", "index()"], answer: "strstr()" },
  { question: "Which function removes a file?", options: ["delete()", "remove()", "unlink()", "dropfile()"], answer: "remove()" }
]
,
cpp : [
  { question: "Which OOP principle does C++ support?", options: ["Encapsulation", "Inheritance", "Polymorphism", "All of these"], answer: "All of these" },
  { question: "Which header file is used for input/output in C++?", options: ["<stdio.h>", "<iostream>", "<string>", "<fstream>"], answer: "<iostream>" },
  { question: "Which operator is overloaded for output in C++?", options: ["<<", ">>", "+", "="], answer: "<<" },
  { question: "Which keyword is used to define a class in C++?", options: ["class", "struct", "object", "define"], answer: "class" },
  { question: "Which access specifier makes members accessible from outside?", options: ["private", "protected", "public", "internal"], answer: "public" },
  { question: "Which function is called when an object is created?", options: ["Constructor", "Destructor", "main()", "init()"], answer: "Constructor" },
  { question: "Which function is called when an object is destroyed?", options: ["Destructor", "free()", "delete()", "exit()"], answer: "Destructor" },
  { question: "Which symbol is used for scope resolution?", options: ["::", ".", "->", ":"], answer: "::" },
  { question: "Which keyword is used to inherit a class?", options: ["inherits", "extends", ":", "implements"], answer: ":" },
  { question: "Which function is used for dynamic memory allocation in C++?", options: ["malloc()", "new", "alloc()", "calloc()"], answer: "new" },
  { question: "Which function releases dynamically allocated memory in C++?", options: ["free()", "delete", "release()", "remove()"], answer: "delete" },
  { question: "Which operator is overloaded for input in C++?", options: ["<<", ">>", "+", "="], answer: ">>" },
  { question: "Which type of inheritance involves multiple base classes?", options: ["Single", "Multiple", "Multilevel", "Hybrid"], answer: "Multiple" },
  { question: "Which keyword is used for constant variables in C++?", options: ["const", "constant", "define", "static"], answer: "const" },
  { question: "Which operator is used for accessing members of a pointer to an object?", options: ["->", ".", "::", "*"], answer: "->" },
  { question: "Which feature allows functions with the same name but different parameters?", options: ["Function Overloading", "Function Overriding", "Polymorphism", "Encapsulation"], answer: "Function Overloading" },
  { question: "Which feature allows a base class pointer to call derived class functions?", options: ["Function Overloading", "Function Overriding", "Virtual Functions", "Templates"], answer: "Virtual Functions" },
  { question: "Which keyword prevents a class from being inherited?", options: ["final", "sealed", "stop", "const"], answer: "final" },
  { question: "Which function is executed before main()?", options: ["Constructor", "Static Initialization", "Global Object Constructor", "Both Static Initialization and Global Object Constructor"], answer: "Both Static Initialization and Global Object Constructor" },
  { question: "Which STL component is used for dynamic arrays?", options: ["vector", "list", "map", "set"], answer: "vector" },
  { question: "Which STL container stores key-value pairs?", options: ["map", "vector", "list", "queue"], answer: "map" },
  { question: "Which operator is used for pointer dereferencing?", options: ["*", "&", "->", "."], answer: "*" },
  { question: "Which function is automatically called at object creation?", options: ["Constructor", "Destructor", "main()", "operator new"], answer: "Constructor" },
  { question: "Which function is automatically called at object destruction?", options: ["Destructor", "free()", "operator delete", "exit()"], answer: "Destructor" },
  { question: "Which keyword is used to create a template function?", options: ["template", "generic", "typename", "Both template and typename"], answer: "template" },
  { question: "Which STL container does not allow duplicate keys?", options: ["set", "multiset", "vector", "map"], answer: "set" },
  { question: "Which STL container allows duplicate keys?", options: ["multiset", "set", "vector", "queue"], answer: "multiset" },
  { question: "Which operator cannot be overloaded?", options: ["::", "+", "()", "[]"], answer: "::" },
  { question: "Which keyword is used to declare an abstract class?", options: ["abstract", "virtual", "pure", "None"], answer: "virtual" },
  { question: "Which syntax declares a pure virtual function?", options: ["virtual void f() = 0;", "virtual void f();", "pure virtual f();", "abstract f();"], answer: "virtual void f() = 0;" },
  { question: "Which cast is used for polymorphic types?", options: ["dynamic_cast", "static_cast", "const_cast", "reinterpret_cast"], answer: "dynamic_cast" },
  { question: "Which feature hides internal details of a class?", options: ["Abstraction", "Encapsulation", "Polymorphism", "Inheritance"], answer: "Encapsulation" },
  { question: "Which operator is used to allocate an array dynamically?", options: ["new[]", "malloc()", "alloc()", "calloc()"], answer: "new[]" },
  { question: "Which keyword is used to refer to the calling object?", options: ["self", "this", "super", "caller"], answer: "this" },
  { question: "Which keyword is used to access a base class constructor?", options: ["base", "super", ":", "this"], answer: ":" },
  { question: "Which operator is used for member access via object?", options: [".", "->", "::", "*"], answer: "." },
  { question: "Which loop type exists in C++?", options: ["for", "while", "do-while", "All of these"], answer: "All of these" },
  { question: "Which function returns the number of elements in a vector?", options: ["size()", "length()", "count()", "capacity()"], answer: "size()" },
  { question: "Which function removes the last element from a vector?", options: ["pop()", "remove()", "pop_back()", "erase()"], answer: "pop_back()" },
  { question: "Which operator is used for memory deallocation of arrays?", options: ["delete[]", "free()", "remove()", "clear()"], answer: "delete[]" },
  { question: "Which type of function can access private members of two classes?", options: ["friend function", "static function", "virtual function", "template function"], answer: "friend function" },
  { question: "Which function is called when copying an object?", options: ["Copy Constructor", "Move Constructor", "Assignment Operator", "Destructor"], answer: "Copy Constructor" },
  { question: "Which keyword is used to prevent overriding of a function?", options: ["final", "sealed", "stop", "const"], answer: "final" },
  { question: "Which constructor takes another object of the same class as an argument?", options: ["Copy Constructor", "Move Constructor", "Default Constructor", "Parametrized Constructor"], answer: "Copy Constructor" },
  { question: "Which operator allocates memory on the heap?", options: ["new", "malloc()", "alloc()", "calloc()"], answer: "new" },
  { question: "Which STL container stores elements in sorted order by default?", options: ["set", "vector", "list", "deque"], answer: "set" },
  { question: "Which STL container implements FIFO?", options: ["queue", "stack", "priority_queue", "deque"], answer: "queue" },
  { question: "Which STL container implements LIFO?", options: ["stack", "queue", "deque", "list"], answer: "stack" },
  { question: "Which loop type is entry-controlled?", options: ["while", "do-while", "for", "Both while and for"], answer: "Both while and for" },
  { question: "Which function in C++ reads a full line including spaces?", options: ["getline()", "cin", "scanf()", "gets()"], answer: "getline()" },
  { question: "Which file mode opens a file for both reading and writing?", options: ["ios::in | ios::out", "ios::readwrite", "ios::rw", "ios::write"], answer: "ios::in | ios::out" },
  { question: "Which operator is used for file output?", options: ["<<", ">>", "put", "write"], answer: "<<" },
  { question: "Which function checks if a file is open?", options: ["is_open()", "opened()", "file_open()", "exists()"], answer: "is_open()" },
  { question: "Which STL container allows insertion/removal from both ends?", options: ["deque", "queue", "stack", "list"], answer: "deque" },
  { question: "Which type of casting is most restrictive?", options: ["dynamic_cast", "static_cast", "const_cast", "reinterpret_cast"], answer: "dynamic_cast" },
  { question: "Which function returns the maximum number of elements a vector can hold?", options: ["max_size()", "capacity()", "reserve()", "limit()"], answer: "max_size()" },
  { question: "Which loop ensures at least one execution?", options: ["do-while", "while", "for", "None"], answer: "do-while" },
  { question: "Which operator is used to compare two strings in C++?", options: ["==", "!=", "compare()", "== or compare()"], answer: "== or compare()" },
  { question: "Which function inserts an element at the end of a vector?", options: ["push_back()", "insert()", "append()", "add()"], answer: "push_back()" },
  { question: "Which feature of C++ allows functions with same name in base and derived?", options: ["Function Overriding", "Overloading", "Encapsulation", "Template"], answer: "Function Overriding" }
],
java : [
  { question: "Which keyword is used to define a class in Java?", options: ["class", "struct", "define", "object"], answer: "class" },
  { question: "Which method is the entry point of a Java program?", options: ["start()", "main()", "init()", "run()"], answer: "main()" },
  { question: "Which keyword is used to inherit a class in Java?", options: ["extends", "implements", "inherits", "super"], answer: "extends" },
  { question: "Which keyword is used to implement an interface?", options: ["extends", "implements", "interface", "inherit"], answer: "implements" },
  { question: "Which package contains the Scanner class?", options: ["java.io", "java.util", "java.lang", "java.net"], answer: "java.util" },
  { question: "Which method of Scanner reads a full line?", options: ["next()", "nextLine()", "readLine()", "read()"], answer: "nextLine()" },
  { question: "Which OOP concept is supported by Java?", options: ["Inheritance", "Encapsulation", "Polymorphism", "All of these"], answer: "All of these" },
  { question: "Which keyword prevents inheritance?", options: ["final", "const", "static", "sealed"], answer: "final" },
  { question: "Which keyword is used to call the parent class constructor?", options: ["super", "this", "base", "parent"], answer: "super" },
  { question: "Which Java keyword is used to create an object?", options: ["new", "malloc", "alloc", "create"], answer: "new" },
  { question: "Which operator is used to access members via object?", options: [".", "->", "::", ":"], answer: "." },
  { question: "Which modifier makes members accessible within package only?", options: ["default", "protected", "private", "public"], answer: "default" },
  { question: "Which access modifier makes members accessible everywhere?", options: ["protected", "default", "public", "private"], answer: "public" },
  { question: "Which keyword is used to define a constant?", options: ["const", "final", "static", "immutable"], answer: "final" },
  { question: "Which method is called before an object is destroyed?", options: ["finalize()", "destroy()", "delete()", "end()"], answer: "finalize()" },
  { question: "Which exception is thrown for array index out of range?", options: ["ArrayIndexOutOfBoundsException", "IndexException", "OutOfBoundsException", "NullPointerException"], answer: "ArrayIndexOutOfBoundsException" },
  { question: "Which class is the root of all classes in Java?", options: ["Object", "Class", "Root", "Base"], answer: "Object" },
  { question: "Which loop ensures execution at least once?", options: ["while", "for", "do-while", "None"], answer: "do-while" },
  { question: "Which keyword is used to create a subclass?", options: ["extends", "implements", "inherits", "subclass"], answer: "extends" },
  { question: "Which type of class cannot be instantiated?", options: ["Abstract", "Final", "Private", "Static"], answer: "Abstract" },
  { question: "Which keyword is used to declare an abstract method?", options: ["abstract", "virtual", "pure", "final"], answer: "abstract" },
  { question: "Which exception is thrown for null object access?", options: ["NullPointerException", "IndexOutOfBoundsException", "ClassCastException", "IOException"], answer: "NullPointerException" },
  { question: "Which keyword is used to handle exceptions?", options: ["catch", "try", "throw", "Both try and catch"], answer: "Both try and catch" },
  { question: "Which block is always executed?", options: ["try", "catch", "finally", "throw"], answer: "finally" },
  { question: "Which keyword is used to manually throw an exception?", options: ["throw", "throws", "raise", "error"], answer: "throw" },
  { question: "Which keyword is used to declare exceptions a method can throw?", options: ["throw", "throws", "exception", "try"], answer: "throws" },
  { question: "Which collection does not allow duplicate elements?", options: ["Set", "List", "Map", "Queue"], answer: "Set" },
  { question: "Which interface is implemented by ArrayList?", options: ["List", "Set", "Map", "Collection"], answer: "List" },
  { question: "Which method adds an element to a list?", options: ["add()", "append()", "insert()", "push()"], answer: "add()" },
  { question: "Which method removes all elements from a list?", options: ["clear()", "removeAll()", "empty()", "deleteAll()"], answer: "clear()" },
  { question: "Which class is used for reading from a file?", options: ["FileReader", "FileInput", "File", "Scanner"], answer: "FileReader" },
  { question: "Which method writes to a file?", options: ["write()", "println()", "output()", "print()"], answer: "write()" },
  { question: "Which Java keyword is used for multiple inheritance?", options: ["extends", "implements", "inherits", "multiple"], answer: "implements" },
  { question: "Which keyword is used for method overloading?", options: ["None", "overload", "override", "final"], answer: "None" },
  { question: "Which keyword is used for method overriding?", options: ["@Override", "overload", "virtual", "final"], answer: "@Override" },
  { question: "Which loop is entry-controlled?", options: ["while", "for", "do-while", "Both while and for"], answer: "Both while and for" },
  { question: "Which method returns length of a string?", options: ["length()", "size()", "getLength()", "count()"], answer: "length()" },
  { question: "Which operator is used for string concatenation?", options: ["+", "&", ".", "concat"], answer: "+" },
  { question: "Which method compares strings ignoring case?", options: ["equalsIgnoreCase()", "compareToIgnoreCase()", "equals()", "compareTo()"], answer: "equalsIgnoreCase()" },
  { question: "Which keyword is used to create an interface?", options: ["interface", "implements", "abstract", "protocol"], answer: "interface" },
  { question: "Which keyword is used to stop loop execution?", options: ["break", "continue", "stop", "exit"], answer: "break" },
  { question: "Which keyword is used to skip to next loop iteration?", options: ["break", "continue", "skip", "pass"], answer: "continue" },
  { question: "Which class is used to work with dates?", options: ["Date", "Calendar", "LocalDate", "All of these"], answer: "All of these" },
  { question: "Which method gets current system time in ms?", options: ["System.currentTimeMillis()", "Date.now()", "Time.now()", "Calendar.time()"], answer: "System.currentTimeMillis()" },
  { question: "Which method pauses thread execution?", options: ["sleep()", "wait()", "pause()", "delay()"], answer: "sleep()" },
  { question: "Which method starts a thread?", options: ["start()", "run()", "begin()", "execute()"], answer: "start()" },
  { question: "Which keyword is used for thread synchronization?", options: ["synchronized", "threadsafe", "lock", "sync"], answer: "synchronized" },
  { question: "Which interface is implemented by threads?", options: ["Runnable", "Threadable", "Process", "Executor"], answer: "Runnable" },
  { question: "Which method is used to check if a thread is alive?", options: ["isAlive()", "alive()", "running()", "exists()"], answer: "isAlive()" },
  { question: "Which keyword is used for packages?", options: ["package", "import", "namespace", "module"], answer: "package" },
  { question: "Which keyword is used to import a package?", options: ["package", "import", "include", "use"], answer: "import" },
  { question: "Which collection stores elements in FIFO?", options: ["Queue", "Stack", "Set", "List"], answer: "Queue" },
  { question: "Which collection stores elements in LIFO?", options: ["Stack", "Queue", "Set", "List"], answer: "Stack" },
  { question: "Which method is used to sort a list?", options: ["Collections.sort()", "list.sort()", "sortList()", "arrange()"], answer: "Collections.sort()" },
  { question: "Which exception is thrown for invalid type casting?", options: ["ClassCastException", "TypeException", "CastException", "InvalidCastException"], answer: "ClassCastException" },
  { question: "Which exception is thrown for division by zero?", options: ["ArithmeticException", "DivideByZero", "ZeroDivision", "MathException"], answer: "ArithmeticException" },
  { question: "Which operator is used to compare object references?", options: ["==", "equals()", "compare()", "is"], answer: "==" },
  { question: "Which method is used to compare object contents?", options: ["equals()", "==", "compare()", "contentEquals()"], answer: "equals()" },
  { question: "Which method is used to get the hash code of an object?", options: ["hashCode()", "getHash()", "code()", "hash()"], answer: "hashCode()" },
  { question: "Which Java version introduced lambda expressions?", options: ["Java 8", "Java 7", "Java 9", "Java 10"], answer: "Java 8" },
  { question: "Which keyword is used to define an enum?", options: ["enum", "enumeration", "enumtype", "define"], answer: "enum" },
  { question: "Which interface provides a method to iterate elements?", options: ["Iterator", "Iterable", "List", "Stream"], answer: "Iterator" },
  { question: "Which stream class is used for byte-oriented output?", options: ["OutputStream", "InputStream", "Reader", "Writer"], answer: "OutputStream" },
  { question: "Which stream class is used for character-oriented input?", options: ["Reader", "InputStream", "Writer", "BufferedInputStream"], answer: "Reader" },
  { question: "Which keyword is used to prevent method overriding?", options: ["final", "static", "sealed", "private"], answer: "final" }
]
};
